name: Build v2rayA snap (artifact)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and configure the build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq wget git python3-yaml
          sudo snap install --classic snapcraft
          sudo python3 -m pip install yq==3.2.3

      - name: Get build version
        run: |
          VERSION=$(python3 -m yq -r '.version' snap/snapcraft.yaml)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Build .snap files
        run: |
          sudo --preserve-env=GITHUB_ACTIONS bash -x snap.sh "${VERSION}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v2raya-snaps
          path: ./*.snap
